name: Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  send-webhook:
    runs-on: windows_latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v3.0.2
      with:
        webhook_url: https://webhook.requestcatcher.com/
